# Recipe for using Dockerfile to build from scratch using Google Cloud Build service.
# use:
#   gcloud builds submit --machine-type=n1-highcpu-8 .
steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --cache-repo=gcr.io/$PROJECT_ID/image/cache
    - --cache=true
    - --no-push
  timeout: 900s

timeout: 910s
options:
  machineType: 'N1_HIGHCPU_8'
