#!/bin/sh
#htplatex debianmeetingresume200708.tex jp,2,sections+
#apt-get install dvi2ps-fontdata-a2n dvi2dvi dvipng

if command -v xhtex > /dev/null 2>&1 ; then
    true
else
    export PATH=/usr/share/tex4ht:$PATH
fi

platex $5 '\makeatletter\def\HCode{\futurelet\HCode\HChar}\def\HChar{\ifx"\HCode\def\HCode"##1"{\Link##1}\expandafter\HCode\else\expandafter\Link\fi}\def\Link#1.a.b.c.{\g@addto@macro\@documentclasshook{\RequirePackage[#1,html]{tex4ht}}\let\HCode\documentstyle\def\documentstyle{\let\documentstyle\HCode\expandafter\def\csname tex4ht\endcsname{#1,html}\def\HCode####1{\documentstyle[tex4ht,}\@ifnextchar[{\HCode}{\documentstyle[tex4ht]}}}\makeatother\HCode '$2'.a.b.c.\input ' $1
platex $5 '\makeatletter\def\HCode{\futurelet\HCode\HChar}\def\HChar{\ifx"\HCode\def\HCode"##1"{\Link##1}\expandafter\HCode\else\expandafter\Link\fi}\def\Link#1.a.b.c.{\g@addto@macro\@documentclasshook{\RequirePackage[#1,html]{tex4ht}}\let\HCode\documentstyle\def\documentstyle{\let\documentstyle\HCode\expandafter\def\csname tex4ht\endcsname{#1,html}\def\HCode####1{\documentstyle[tex4ht,}\@ifnextchar[{\HCode}{\documentstyle[tex4ht]}}}\makeatother\HCode '$2'.a.b.c.\input ' $1
platex $5 '\makeatletter\def\HCode{\futurelet\HCode\HChar}\def\HChar{\ifx"\HCode\def\HCode"##1"{\Link##1}\expandafter\HCode\else\expandafter\Link\fi}\def\Link#1.a.b.c.{\g@addto@macro\@documentclasshook{\RequirePackage[#1,html]{tex4ht}}\let\HCode\documentstyle\def\documentstyle{\let\documentstyle\HCode\expandafter\def\csname tex4ht\endcsname{#1,html}\def\HCode####1{\documentstyle[tex4ht,}\@ifnextchar[{\HCode}{\documentstyle[tex4ht]}}}\makeatother\HCode '$2'.a.b.c.\input ' $1
dvi2dvi -F a2n ${1/.tex/.dvi} > ${1/.tex/.dvi.tmp}
mv ${1/.tex/.dvi.tmp} ${1/.tex/.dvi}
tex4ht -f/$1   -itex4ht/ht-fonts/mozilla/nttsub/$3
t4ht -f/$1 $4 -dhtml/

# c.f. bug #XXXX
for A in html/*.html; do
    sed -i -e 's,src="image.*/,src=",' "$A"
    sed -i -f tex4ht/dnp-trim.sed "$A"
    rm "$A.tmp"
    while ! diff "$A.tmp" "$A" > /dev/null ; do
	mv "$A.tmp" "$A" || true
	echo "Modifying $A..."
	sed -f tex4ht/dnp-span.sed "$A" > "$A.tmp"
    done
done
