application: debianmeeting
version: 20
runtime: python
api_version: 1

handlers:
- url: /batch/.*
  script: debianmeeting.py
  login: admin

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: debianmeeting.py
  login: required

