application: debianmeeting
version: 7
runtime: python
api_version: 1

handlers:
- url: /enquete/sendmailworker
  script: debianmeeting.py
  login: admin

- url: /stylesheets
  static_dir: stylesheets

- url: /eventsimple
  script: debianmeeting.py

- url: /event
  script: debianmeeting.py

- url: /.*
  script: debianmeeting.py
  login: required

