application: debianmeeting
version: 14
runtime: python
api_version: 1

handlers:
- url: /enquete/sendmailworker
  script: debianmeeting.py
  login: admin

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: debianmeeting.py
  login: required

