# Recipe for refreshing the docker images on gcr.io. Should be ran once a month?
# use:
#   cd utils/docker && gcloud builds submit .  # to refresh the docker files.
steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --destination=gcr.io/$PROJECT_ID/monthly-report-builder
    - --cache=true
    - --dockerfile=Dockerfile.buster
  timeout: 500s

- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --destination=gcr.io/$PROJECT_ID/monthly-report-builder-stretch
    - --cache=true
    - --dockerfile=Dockerfile.stretch
  timeout: 500s

timeout: 1000s
 
