# Recipe for refreshing the docker images on gcr.io. Should be ran once a month?
# use:
#   cd utils/docker && gcloud builds submit .  # to refresh the docker files.
steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --destination=gcr.io/$PROJECT_ID/monthly-report-builder-bookworm
    - --cache=true
    - --dockerfile=Dockerfile.bookworm
    - --compressed-caching=false
  timeout: 600s

- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --destination=gcr.io/$PROJECT_ID/monthly-report-builder
    - --cache=true
    - --dockerfile=Dockerfile.bullseye
    - --compressed-caching=false
  timeout: 600s

timeout: 2000s
 
